### ISSUE TITLE
get_source_data non-numeric error

### ISSUE THREAD

**Issue by cramirezs** [vijaybioinfo/clustering#1]
When I try to run the pipeline the following error appears:

```
Error in all0(object[lower.tri(object)]) : 
  Argument must be numeric-like atomic vector
Calls: get_source_data ... <Anonymous> -> isTriangular -> isTriangular -> all0
Execution halted
```

**Comment by vijaybioinfo** [comment]
Sometimes this error appears when we give `outs/aggregation.csv` to the `input_expression` parameter. Truncating `aggregation.csv` or changing it to `filtered_feature_bc_matrix` should do the job.

Though we're interested in taking `aggregation.csv` too in case we want to load each library and then merge rather than the aggregation. I will look into how to consolidate this.
